name: Scrape Data
on:
  workflow_dispatch:
  schedule:
    - cron:  '1 8,20 * * *' # Every 12 hours. Ref https://crontab.guru/examples.html
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: script
      run: ./script.sh > _PATH/myFile.txt
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        BRANCH_NAME: main
